### ISSUE TITLE
неправильная индикация компаса

### ISSUE THREAD

**Issue by ilitaI2P** [SmylerMC/terramap#32]
![image](https://user-images.githubusercontent.com/81111889/120635887-a1d15380-c475-11eb-8dd9-ce77d267cdb7.png)

**Comment by SmylerMC** [comment]
Hello there, would

**Comment by SmylerMC** [comment]
Hello there, could you please re-open this issue and post it in English please ? I don't know what I'm supposed to see in this screenshot here.
I understand why having to use an online translator could be bothersome, but I'd rather keep the entire repo in English for coherence.
