### ISSUE TITLE
[Feature request] map offset 

### ISSUE THREAD

**Issue by Hing196** [SmylerMC/terramap#37]
This mod might be more useful if you could customize the offset.
For example, my custom map has an accurate outline. If it can be offset to the correct location, I can directly use the tpll to build via this mod.

**Comment by SmylerMC** [comment]
Hello,
This feature has already been implemented. 

https://github.com/SmylerMC/terramap/assets/19222559/4bc4e1a8-ae6b-4b47-89d6-9f34b5eff741

You will need the latest development build from Discord for it work with the Minimap as featured in the video.

**Comment by Hing196** [comment]
Oh awesome
