### ISSUE TITLE
terra 1 to 1 and new Version: 0.1.5 and your mod terramap work not to 100 Percent perfect

### ISSUE THREAD

**Issue by Titoo8899** [SmylerMC/terramap#5]
Hi,
in the new Update today 20.07.2020 was a new Update of the terra 1 to 1 and have cool new Features. But one little Problem have I with your mod.  To see the World I must open your Mod in Terrain see Screenshot 1. But the other 2 Overlays with Openstreetmap work not I can click this but the Mod load this not only the Terrain Overlay load normal. Please fix this. I play on a Solo Map of the Earth.

![2020-07-20_19 59 34](https://user-images.githubusercontent.com/42325138/87970239-ba39b900-cac3-11ea-8684-bc849b6636ba.png)
![2020-07-20_20 00 11](https://user-images.githubusercontent.com/42325138/87970240-bd34a980-cac3-11ea-9bf9-eba0b56eaf9b.png)
![2020-07-20_20 00 22](https://user-images.githubusercontent.com/42325138/87970256-c0c83080-cac3-11ea-839a-b72a4f5fe268.png)
![2020-07-20_20 00 34](https://user-images.githubusercontent.com/42325138/87970257-c0c83080-cac3-11ea-9800-1598e3ca71fd.png)

**Comment by SmylerMC** [comment]
Are you certain this problem is related to the Terra121 update? See really see no reason why it would change anything on that side.

**Comment by SmylerMC** [comment]
I cannot reproduce your issue. It's not linked with Terra121. The central OSM servers may have been down lately, so please try again and let me know if it now works. If not I'll need your log file to investigate the issue.
